export const mainTypes = {
	ADD_CHARACTER: "ADD_CHARACTER",
	ADD_CHARACTERISTIC: "ADD_CHARACTERISTIC",
	ADD_RIGHT_ANSWER: "ADD_RIGHT_ANSWER",
	ADD_WRONG_ANSWER: "ADD_WRONG_ANSWER",
	DELETE_RIGHT_ANSWERS: "DELETE_RIGHT_ANSWERS",
	DELETE_WRONG_ANSWERS: "DELETE_WRONG_ANSWERS",
};
